name: "Terraform"

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 

jobs:
  terraform:
    defaults:
      run:
        shell: bash

    name: "Terraform"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        # with:
        #   terraform_version: 1.1.7
          # terraform_wrapper: true
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        # if: github.event_name == 'pull_request'
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Run Cron
        run: |
          npm run something